#!/usr/bin/env python3
# Sacha Panasuik
# sachapan@gmail.com
# this script removes blank lines and lines that begin with #
#
import sys

counter = 1
while True:
    line = sys.stdin.readline()
    if not line:
        break
    line2 = line.replace("\n","")
    line3 = line2.lstrip();
    if line3.startswith("#"):
        continue
    if line2:
        print(line2)
    counter += 1
